# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('cedula', models.CharField(max_length=13)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9)),
                ('celular', models.CharField(max_length=14)),
                ('direccion', models.CharField(max_length=500)),
                ('correo', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
