# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_I_persona', models.CharField(max_length=10)),
                ('tipo_usuarios', models.CharField(choices=[('U', 'usuarios'), ('C', 'clientes')], max_length=12)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('celular', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=160)),
                ('telefono', models.CharField(max_length=7)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_ingreso', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
