""" Formating Strings"""


# Longitud de cadenas. 
# Asignar a una variable la cadena "KiriosNet"
# Imprimir el numero de caracteres de la variable

String="KiriosNet"
print(String)


# Imprimir el primer caracter de la variable


# Imprimir el ultimo caracter de la variable

# Imprimir el caracter 7 de la variable



# Imprimir los primeros 6 digitos de la variable

# Imprimir el mensaje formateado "Usted esta en Variable por 15.05 minutos"