# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-16 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_horas', models.CharField(max_length=30)),
                ('tipo_servicios', models.CharField(choices=[('D_C', 'De Campo'), ('E_S', 'Evento Social'), ('Ext', 'Extremos')], max_length=3)),
                ('lugar', models.CharField(max_length=60)),
                ('tipo_evento', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotografo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
