# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-10-20 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_servicios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Tipo_Reserva'),
        ),
    ]
