# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='n_horas',
            field=models.IntegerField(default=0),
        ),
    ]
