# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-11-03 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_auto_20171103_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
